Usage Docs for m-agent and process-kill Experiment
litmuschaos/m-agent pull request #8
Opened 2022-05-12 05:46 UTC by neelanjan00

Signed-off-by: Neelanjan Manna <neelanjan.manna@harness.io>

## Why We Need This PR
Adds a Usage doc for:
- How to install and setup m-agent
- How to run the process-kill experiment in ChaosCenter

## Which Issue This PR Fixes 
fixes #7

**Checklist:**
-   [x] Fixes #<issue number>
-   [x] PR messages has document related information
-   [ ] Labelled this PR & related issue with `breaking-changes` tag
-   [ ] PR messages has breaking changes related information
-   [ ] Labelled this PR & related issue with `requires-upgrade` tag
-   [ ] PR messages has upgrade related information
-   [ ] Commit has unit tests
-   [ ] Commit has integration tests
-   [ ] E2E run Required for the changes

2022-05-12 09:30 UTC, avaakash requested changes

2022-05-12 09:30 UTC, avaakash commented on USAGE.md
> +A simple chaos experiment that you can execute using m-agent is process-kill experiment. As the name suggests, a process-kill chaos causes any number of processes in your target machine to be killed
```suggestion
A simple chaos experiment that you can execute using m-agent is the process-kill experiment. As the name suggests, process-kill chaos causes any number of processes in your target machine to be killed ungracefully. In this document, we'll learn how we can execute this chaos experiment using ChaosCenter.
```

2022-05-12 09:30 UTC, avaakash commented on USAGE.md
> +Choose the duration through which you want the token to remain valid in the prompt. If you want to specify a different expiry duration for the token, you can use [non-interactive](./README.md#usage)
```suggestion
Choose the duration for which you want the token to remain valid in the prompt. If you want to specify a different expiry duration for the token, you can use [non-interactive](./README.md#usage) token generation.
```

2022-05-12 09:30 UTC, avaakash commented on USAGE.md
> +Upon adding the ChaosHub, you will be able to access the os/process-kill experiment charts.
```suggestion
Upon adding the ChaosHub, you will be able to access the process-kill experiment charts which are inside the os category.
```
os/process-kill could be interpreted more like os or process-kill by a new user

2022-05-12 09:30 UTC, avaakash commented on USAGE.md
> +Create a Chaos Workflow, and choose the m-agent ChaosHub which you had previously added. Then add the os/process-kill experiment and tune the experiment by adding the target PIDs in `PROCESS_IDS` as
```suggestion
Create a Chaos Workflow, and choose the m-agent ChaosHub that you had previously added. Then add the os/process-kill experiment and tune the experiment by adding the target PIDs in `PROCESS_IDS` as comma-separated values. You can leave the other settings as default.
```

2022-05-12 09:30 UTC, avaakash commented on USAGE.md
> +You can add any of the Litmus Probes for this experiment as well. The cmdProbe in this case will execute in the target machine so that you can validate your chaos hypothesis condition within the remo
```suggestion
You can add Litmus Probes to this experiment as well. The cmdProbe in this case will execute in the target machine so that you can validate your chaos hypothesis condition within the remote target machine.
```
`any of the` is not required, as the benefit is already clear by saying `probes`

2022-05-12 10:29 UTC, avaakash approved these changes

2022-05-24 10:02 UTC, Jonsy13 approved these changes

2022-05-24 11:08 UTC, merged